/**
 * A page object, in Playwright's words.
 *
 * Locators live here and only here: healing one that drifted is an edit to one file, not to
 * every spec that touched the element. That is the whole reason the IR holds a reference
 * (`{page, element}`) rather than a selector.
 */

import { lineComment, stringLiteral } from "../../codegen/naming.js";
import type { PageObject } from "../../codegen/types.js";
import { fallbackExpression, locatorExpression } from "./locators.js";

/**
 * Members the class defines itself, which an inspected element may therefore not be called.
 *
 * An element named `page` would redeclare the constructor property and produce a class that
 * does not compile; one named `goto` would silently replace the navigation method. Inspection
 * reads these names off the application, so it can propose either at any time.
 */
const RESERVED_MEMBERS = new Set(["page", "goto", "constructor"]);

export function renderPageObject(page: PageObject): string {
  const lines: string[] = [];
  lines.push('import type { Locator, Page } from "@playwright/test";');
  lines.push("");
  lines.push("/**");
  lines.push(` * ${page.name}${page.route ? ` — ${page.route}` : ""}.`);
  lines.push(" *");
  lines.push(
    " * Generated by Specra from inspected locators. Edit freely: this file is yours, and a",
  );
  lines.push(" * regeneration proposes a diff rather than overwriting your changes.");
  lines.push(" */");
  lines.push(`export class ${page.name} {`);
  lines.push("  constructor(readonly page: Page) {}");
  lines.push("");

  for (const element of page.elements) {
    if (RESERVED_MEMBERS.has(element.name)) {
      // Refusing beats emitting a class that cannot compile, and beats renaming behind the
      // user's back: the element is real, and its name is a decision inspection has to redo.
      throw new Error(
        `${page.name} has an element named "${element.name}", which is a member the page object` +
          ` already defines. Rename it in the page object before generating.`,
      );
    }
    if (element.fallback) {
      const fallback = fallbackExpression(element);
      lines.push(
        `  ${lineComment(`fallback: ${element.fallback.strategy} ${element.fallback.value}${fallback ? "" : ""}`)}`,
      );
    }
    if (element.confidence !== undefined) {
      lines.push(`  ${lineComment(`confidence ${element.confidence.toFixed(2)}`)}`);
    }
    lines.push(`  get ${element.name}(): Locator {`);
    lines.push(`    return ${locatorExpression(element)};`);
    lines.push("  }");
    lines.push("");
  }

  if (page.route !== undefined) {
    lines.push("  async goto(): Promise<void> {");
    lines.push(`    await this.page.goto(${stringLiteral(page.route)});`);
    lines.push("  }");
  } else {
    // No inspected route yet: the page is reached by navigating within the application, and a
    // goto() that guessed a path would be a locator guess by another name.
    lines.push("  async goto(): Promise<void> {");
    lines.push(
      `    throw new Error(${stringLiteral(`${page.name} has no route yet — inspect it, or reach it through the application`)});`,
    );
    lines.push("  }");
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}
