/**
 * The project skeleton (07-git.md), written once when a repository is first connected.
 *
 * Everything here answers one test: clone the user's repository, `pnpm install`,
 * `npx playwright test`, and the suite runs with no reference to Specra. So the config reads
 * `BASE_URL` from the environment rather than calling anything, the parameter accessors throw a
 * sentence a human can act on, and nothing at test time reads `.specra/`.
 */

import type { Parameter } from "@specra/test-model";

import { stringLiteral } from "../../codegen/naming.js";

/** Pinned rather than floating: a generated project that installs a different Playwright next month is not reproducible. */
export const PLAYWRIGHT_VERSION = "1.62.1";

/** The engine's test package and config file name, so no caller above this folder types them. */
export function engineTestPackage(): string {
  return "@playwright/test";
}

export function configFileName(): string {
  return "playwright.config.ts";
}

export function renderPackageJson(projectName: string): string {
  const pkg = {
    name: projectName,
    version: "0.1.0",
    private: true,
    type: "module",
    scripts: {
      test: "playwright test",
      "test:headed": "playwright test --headed",
      "test:ui": "playwright test --ui",
      report: "playwright show-report",
      browsers: "playwright install chromium",
    },
    devDependencies: {
      [engineTestPackage()]: `^${PLAYWRIGHT_VERSION}`,
      "@types/node": "^20",
      typescript: "^5",
    },
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

export function renderPlaywrightConfig(browsers: string[]): string {
  const projects = browsers
    .map((browser) => {
      const device = DEVICES[browser] ?? "Desktop Chrome";
      return `    { name: ${stringLiteral(browser)}, use: { ...devices[${stringLiteral(device)}] } },`;
    })
    .join("\n");

  return `import { defineConfig, devices } from "@playwright/test";

/**
 * Generated by Specra, then owned by you.
 *
 * The base URL comes from the environment so the same suite runs against dev, staging and CI.
 * Nothing here calls Specra: this project runs on its own, which is the point.
 */
export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  forbidOnly: Boolean(process.env.CI),
  retries: process.env.CI ? 2 : 0,
  reporter: process.env.CI ? "github" : "list",
  use: {
    baseURL: process.env.BASE_URL ?? "http://localhost:3000",
    trace: "on-first-retry",
    video: "retain-on-failure",
    screenshot: "only-on-failure",
  },
  projects: [
${projects}
  ],
});
`;
}

/**
 * The environment fixture: every declared parameter as an accessor.
 *
 * A secret's value never appears in the repository — only its name, read from the process
 * environment the runner was dispatched with. A missing one fails with the name of the variable
 * to set, before a browser starts, rather than filling a field with `undefined`.
 */
export function renderEnvironmentFixture(parameters: Parameter[]): string {
  const lines: string[] = [];
  lines.push("/**");
  lines.push(" * Test parameters, read from the environment.");
  lines.push(" *");
  lines.push(
    " * Generated by Specra. Values live in your CI secrets or your local .env — never in",
  );
  lines.push(" * this repository, and never in a Specra database.");
  lines.push(" */");
  lines.push("");
  lines.push("function read(name: string, required: boolean): string {");
  lines.push("  const value = process.env[name];");
  lines.push('  if (value === undefined || value === "") {');
  lines.push("    if (required) {");
  lines.push(
    "      throw new Error(`${name} is not set. Add it to the environment this suite runs in.`);",
  );
  lines.push("    }");
  lines.push('    return "";');
  lines.push("  }");
  lines.push("  return value;");
  lines.push("}");
  lines.push("");

  for (const parameter of parameters) {
    const variable = envVariableName(parameter.name);
    const required = parameter.required !== false;
    if (parameter.secret) {
      lines.push(`/** Secret. Read from ${variable}; never logged, never committed. */`);
    } else if (parameter.description) {
      lines.push(`/** ${parameter.description} */`);
    }
    lines.push(
      `export const ${parameter.name} = (): string => read(${stringLiteral(variable)}, ${required});`,
    );
    lines.push("");
  }

  return lines.join("\n");
}

/** `couponCode` → `COUPON_CODE`: the shape a person expects in a .env file. */
export function envVariableName(parameterName: string): string {
  return parameterName
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^A-Za-z0-9]+/g, "_")
    .toUpperCase();
}

/**
 * `.specra/project.json` — what wrote this project, and how.
 *
 * Committed on purpose so the repository is self-describing, and read by nothing at test time.
 */
export function renderProjectDescriptor(adapterVersion: string, browsers: string[]): string {
  const descriptor = {
    engine: "playwright",
    adapterVersion,
    conventions: {
      layout: "page-object-model",
      tests: "tests/<area>/<case>.spec.ts",
      pages: "pages/<Name>Page.ts",
      flows: "flows/<name>.flow.ts",
      parameters: "fixtures/environment.ts",
    },
    browsers,
  };
  return `${JSON.stringify(descriptor, null, 2)}\n`;
}

const DEVICES: Record<string, string> = {
  chromium: "Desktop Chrome",
  firefox: "Desktop Firefox",
  webkit: "Desktop Safari",
};
