/**
 * The spec file: one IR, one test.
 *
 * The projection is mechanical on purpose. Everything a reader could argue about — which page,
 * which element, which parameter — was decided upstream in the IR, so this file has no judgement
 * left to make and can therefore be byte-identical on every run.
 */

import { isPageTarget, type TestModel, type TestStep } from "@specra/test-model";

import { kebabCase, lineComment, pageVariable, stringLiteral } from "../../codegen/naming.js";
import type { CodegenRequest } from "../../codegen/types.js";
import { renderStep, type StepContext } from "./steps.js";

const INDENT = "  ";

export interface SpecRender {
  contents: string;
  unresolved: { stepId: string; page: string; element?: string }[];
}

export function renderSpec(request: CodegenRequest): SpecRender {
  const { model, pages, options } = request;
  const known = new Map(
    pages.map((page) => [page.name, new Set(page.elements.map((element) => element.name))]),
  );
  const unresolved: SpecRender["unresolved"] = [];
  const context: StepContext = {
    knownPages: known,
    onUnresolved: (step, page, element) => unresolved.push({ stepId: step.id, page, element }),
  };

  const usedPages = pagesUsedBy(model, known);
  const usedFlows = flowsUsedBy(model);
  const parameters = model.parameters ?? [];

  // `expect` only when something is asserted, so the generated file has no unused import.
  const asserts = allSteps(model).some(
    (step) => step.action === "assert" || step.action === "waitFor",
  );

  const lines: string[] = [];
  lines.push(
    asserts
      ? 'import { expect, test } from "@playwright/test";'
      : 'import { test } from "@playwright/test";',
  );
  lines.push("");
  for (const page of usedPages) {
    lines.push(`import { ${page} } from "../${depth(options.area)}pages/${page}.js";`);
  }
  for (const flow of usedFlows) {
    lines.push(
      `import { ${flow}Flow } from "../${depth(options.area)}flows/${kebabCase(flow)}.flow.js";`,
    );
  }
  if (parameters.length > 0) {
    lines.push(
      `import { ${parameters.map((p) => p.name).join(", ")} } from "../${depth(options.area)}fixtures/environment.js";`,
    );
  }
  lines.push("");

  // The traceability line: which manual case this came from, readable in the repository by
  // someone who has never opened Specra.
  lines.push(`/** ${options.reference} — generated by Specra from the Test Model. */`);

  const tags = (model.tags ?? []).map((tag) => `@${tag}`).join(" ");
  const title = tags ? `${model.name} ${tags}` : model.name;
  lines.push(`test(${stringLiteral(title)}, async ({ page }) => {`);

  if (model.description) {
    // Through `lineComment`, like every other piece of IR text: this one is multi-line far more
    // often than a step's, and an unflattened newline ends the comment.
    lines.push(`${INDENT}${lineComment(model.description)}`);
  }

  for (const page of usedPages) {
    lines.push(`${INDENT}const ${pageVariable(page)} = new ${page}(page);`);
  }
  if (usedPages.length > 0) {
    lines.push("");
  }

  emitSection(lines, "Setup", model.setup, context);
  emitSection(lines, null, model.steps, context);
  emitSection(lines, "Teardown", model.teardown, context);

  lines.push("});");
  lines.push("");
  return { contents: lines.join("\n"), unresolved };
}

function emitSection(
  lines: string[],
  heading: string | null,
  steps: TestStep[] | undefined,
  context: StepContext,
): void {
  if (!steps || steps.length === 0) {
    return;
  }
  if (heading) {
    lines.push(`${INDENT}// ${heading}`);
  }
  for (const step of steps) {
    for (const line of renderStep(step, context)) {
      lines.push(`${INDENT}${line}`);
    }
  }
  lines.push("");
}

/** Every page object the spec instantiates, in first-use order so the output is stable. */
function pagesUsedBy(model: TestModel, known: Map<string, Set<string>>): string[] {
  const used: string[] = [];
  for (const step of allSteps(model)) {
    for (const target of [step.target, step.to]) {
      if (
        target &&
        isPageTarget(target) &&
        known.has(target.page) &&
        !used.includes(target.page)
      ) {
        used.push(target.page);
      }
    }
  }
  return used;
}

function flowsUsedBy(model: TestModel): string[] {
  const used: string[] = [];
  for (const step of allSteps(model)) {
    if (step.action === "useFlow" && step.flow && !used.includes(step.flow)) {
      used.push(step.flow);
    }
  }
  return used;
}

function allSteps(model: TestModel): TestStep[] {
  return [...(model.setup ?? []), ...model.steps, ...(model.teardown ?? [])];
}

/** `tests/auth/x.spec.ts` is two levels down, `tests/x.spec.ts` one. */
function depth(area: string | undefined): string {
  return area ? "../" : "";
}
