/**
 * Determinism, as the only test that can actually prove it.
 *
 * Every generated byte is checked into `__golden__/`. A change to the adapter that alters one
 * character fails here, and the diff in the failure is exactly the diff a user would have seen
 * in their repository — which is the review the golden file exists to force.
 *
 * Run with `UPDATE_GOLDEN=1 pnpm --filter specra-runner test` to rewrite them, then read the
 * git diff before committing. That reading is the point; skipping it makes the files decoration.
 *
 * The snapshot is taken *after* prettier, because that is what lands in the user's repository:
 * a golden file of the pre-formatting bytes would be a record of an intermediate nobody ever
 * sees, and would go on matching while the delivered file changed.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { describe, expect, it } from "vitest";

import {
  CHECKOUT_PAGES,
  CLEAR_CART_FLOW,
  HOME_PAGES,
  LOGIN_FLOW,
  LOGIN_PAGES,
  irFixture,
  options,
} from "./fixtures.js";
import { generate } from "./generate.js";
import { formatFiles } from "./validate.js";
import type { CodegenRequest } from "./types.js";

const GOLDEN = path.join(path.dirname(fileURLToPath(import.meta.url)), "__golden__");
const UPDATE = process.env.UPDATE_GOLDEN === "1";

const CASES: { name: string; request: CodegenRequest }[] = [
  {
    name: "minimal",
    request: {
      model: irFixture("minimal"),
      pages: HOME_PAGES,
      options: options({ reference: "TC-1" }),
    },
  },
  {
    name: "login",
    request: {
      model: irFixture("login"),
      pages: LOGIN_PAGES,
      options: options({ reference: "TC-104", area: "auth" }),
    },
  },
  {
    name: "checkout",
    request: {
      model: irFixture("checkout"),
      pages: CHECKOUT_PAGES,
      flows: [
        { name: "login", model: LOGIN_FLOW },
        { name: "clearCart", model: CLEAR_CART_FLOW },
      ],
      options: options({ reference: "TC-77", area: "checkout" }),
    },
  },
  {
    name: "scaffold",
    request: {
      model: irFixture("login"),
      pages: LOGIN_PAGES,
      options: options({
        reference: "TC-104",
        area: "auth",
        scaffold: true,
        projectName: "acme-e2e",
        browsers: ["chromium", "firefox", "webkit"],
      }),
    },
  },
];

/** One text blob per case: paths and bodies, so a moved file is as visible as a changed one. */
async function snapshot(request: CodegenRequest): Promise<string> {
  const result = generate(request);
  const files = await formatFiles(result.files);
  const parts = files.map((file) => `=== ${file.path} (${file.role}) ===\n${file.contents}`);
  if (result.unresolved.length > 0) {
    parts.push(`=== unresolved ===\n${JSON.stringify(result.unresolved, null, 2)}\n`);
  }
  return parts.join("\n");
}

describe("the Playwright adapter is a pure projection", () => {
  it.each(CASES)("$name matches its golden file", async ({ name, request }) => {
    const actual = await snapshot(request);
    const file = path.join(GOLDEN, `${name}.txt`);

    if (UPDATE || !existsSync(file)) {
      mkdirSync(GOLDEN, { recursive: true });
      writeFileSync(file, actual);
    }

    expect(actual).toEqual(readFileSync(file, "utf8"));
  });

  it.each(CASES)("$name generates identical bytes when run twice", async ({ request }) => {
    expect(await snapshot(request)).toEqual(await snapshot(request));
  });

  it.each(CASES)(
    "$name is byte-identical whatever order the pages arrive in",
    async ({ request }) => {
      const reversed = { ...request, pages: [...request.pages].reverse() };
      // File order is normalised by path, and page objects are rendered per file, so shuffling
      // the input must not move a single byte. Only the spec's own import order is allowed to
      // depend on the IR — and that comes from step order, not from this array.
      const a = await snapshot(request);
      const b = await snapshot(reversed);
      expect(sortedSections(b)).toEqual(sortedSections(a));
    },
  );
});

function sortedSections(snapshotText: string): string[] {
  return snapshotText
    .split("\n=== ")
    .map((section) => section.trim())
    .sort();
}
