/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/notes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one note */
        get: operations["get"];
        /** Replace a note; clears its index flag because the content changed */
        put: operations["update"];
        post?: never;
        /** Delete a note and drop its embeddings */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notes, newest first, with optional full-text and tag filters */
        get: operations["list"];
        put?: never;
        /** Create a note */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/{id}/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chunk, embed and store this note in pgvector so RAG can retrieve it */
        post: operations["index"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask the model, keeping conversation history in Postgres */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Same as /chat but streams tokens over server-sent events
         * @description Each `token` event carries the token as a JSON string. Clients must JSON.parse it.
         */
        post: operations["stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** RAG: retrieve indexed note chunks from pgvector, then answer from them */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Similarity search only, no generation — shows what RAG would feed the model */
        get: operations["retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report the active chat and embedding providers */
        get: operations["providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/chat/{conversationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Forget one conversation */
        delete: operations["clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NoteRequest: {
            /** @example Kickoff notes */
            title: string;
            /** @example We agreed to ship the pgvector spike first. */
            content: string;
            /**
             * @example [
             *       "meeting",
             *       "q3"
             *     ]
             */
            tags?: string[];
        };
        NoteResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            content?: string;
            tags?: string[];
            /** Format: date-time */
            indexedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ChatRequest: {
            /** @example Summarise what I wrote about pgvector. */
            message: string;
            /**
             * @description Conversation id. Reuse it to keep history; omit for a fresh thread.
             * @example default
             */
            conversationId?: string;
        };
        ChatReply: {
            content?: string;
            /** @example default */
            conversationId?: string;
            /**
             * @description Which provider actually answered
             * @example anthropic
             */
            provider?: string;
            /** @example claude-sonnet-4-5 */
            model?: string;
        };
        ServerSentEventString: unknown;
        AskRequest: {
            /** @example What did we decide about the database? */
            question: string;
            /**
             * Format: int32
             * @default 4
             */
            topK: number;
            /**
             * Format: double
             * @description Minimum cosine similarity, 0..1
             * @default 0.5
             */
            similarityThreshold: number;
        };
        AskReply: {
            answer?: string;
            /** @description Chunks retrieved from pgvector that grounded the answer */
            sources?: components["schemas"]["Source"][];
            provider?: string;
            model?: string;
        };
        Source: {
            /** @example Kickoff notes */
            title?: string;
            /** @description Id of the note this chunk came from */
            noteId?: string;
            /** @description The retrieved chunk, truncated for display */
            excerpt?: string;
            /**
             * Format: double
             * @example 0.83
             */
            score?: number;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        /** @description A page of results. */
        PageResponseNoteResponse: {
            content?: components["schemas"]["NoteResponse"][];
            /**
             * Format: int32
             * @example 0
             */
            page?: number;
            /**
             * Format: int32
             * @example 20
             */
            size?: number;
            /**
             * Format: int64
             * @example 137
             */
            totalElements?: number;
            /**
             * Format: int32
             * @example 7
             */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
        /** @description Which model providers are wired in right now. Everything here is driven by spring.ai.model.* properties, so it changes without recompiling. */
        ProviderInfo: {
            /** @example anthropic */
            chatProvider?: string;
            /** @example transformers */
            embeddingProvider?: string;
            /** @example AnthropicChatModel */
            chatModelType?: string;
            /** @example TransformersEmbeddingModel */
            embeddingModelType?: string;
            /**
             * Format: int32
             * @description Vector width the pgvector table must match
             * @example 384
             */
            embeddingDimensions?: number;
            /** @description Providers whose starter is on the classpath */
            availableProviders?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NoteResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NoteResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query: {
                /** @description Matches title or content, case-insensitive */
                q?: string;
                /** @description Exact tag match */
                tag?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseNoteResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NoteResponse"];
                };
            };
        };
    };
    index: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NoteResponse"];
                };
            };
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChatReply"];
                };
            };
        };
    };
    stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ServerSentEventString"][];
                };
            };
        };
    };
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AskReply"];
                };
            };
        };
    };
    retrieve: {
        parameters: {
            query: {
                q: string;
                topK?: number;
                threshold?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Source"][];
                };
            };
        };
    };
    providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProviderInfo"];
                };
            };
        };
    };
    clear: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
