-- Tenancy and projects (04-database.md).
--
-- Two conventions run through every table below:
--   * uuid primary keys, generated by the application, as V1 already does;
--   * workspace_id on everything under a workspace, even where a join would reach it —
--     tenancy filtering that depends on a join is tenancy filtering that gets forgotten.
--
-- Enum-ish columns are varchar + CHECK rather than a Postgres enum, so adding a value is an
-- INSERT-free migration instead of an ALTER TYPE that takes a lock.

CREATE TABLE users (
    id            uuid         PRIMARY KEY,
    email         varchar(320) NOT NULL,
    display_name  varchar(120) NOT NULL,
    -- Null until local sign-in exists; an SSO-only user keeps it null forever.
    password_hash varchar(200),
    created_at    timestamptz  NOT NULL,
    updated_at    timestamptz  NOT NULL,
    version       bigint       NOT NULL DEFAULT 0,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE workspaces (
    id         uuid         PRIMARY KEY,
    name       varchar(120) NOT NULL,
    -- What appears in a URL and what a human types; unique across the installation.
    slug       varchar(64)  NOT NULL,
    created_at timestamptz  NOT NULL,
    updated_at timestamptz  NOT NULL,
    version    bigint       NOT NULL DEFAULT 0,
    CONSTRAINT uq_workspaces_slug UNIQUE (slug)
);

CREATE TABLE workspace_members (
    id           uuid        PRIMARY KEY,
    workspace_id uuid        NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    user_id      uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role         varchar(16) NOT NULL,
    created_at   timestamptz NOT NULL,
    updated_at   timestamptz NOT NULL,
    version      bigint      NOT NULL DEFAULT 0,
    CONSTRAINT uq_workspace_members UNIQUE (workspace_id, user_id),
    CONSTRAINT ck_workspace_members_role CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER'))
);

-- The workspace's own model provider, key and budget (BYOK). One per workspace; a workspace
-- without a row falls back to the installation's configuration. The key is stored encrypted
-- and never leaves the API — reads report "set" or "not set", never the value.
CREATE TABLE ai_accounts (
    id                 uuid         PRIMARY KEY,
    workspace_id       uuid         NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    provider           varchar(32)  NOT NULL,
    api_key_cipher     text,
    chat_model         varchar(120),
    embedding_model    varchar(120),
    monthly_budget_usd numeric(12, 2),
    created_at         timestamptz  NOT NULL,
    updated_at         timestamptz  NOT NULL,
    version            bigint       NOT NULL DEFAULT 0,
    CONSTRAINT uq_ai_accounts_workspace UNIQUE (workspace_id)
);

-- One project is exactly one Git repository and one default branch. Two repositories is two
-- projects, which is what keeps "where does this code go" answerable without a resolution step.
CREATE TABLE projects (
    id           uuid         PRIMARY KEY,
    workspace_id uuid         NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    -- Short human handle, uppercase: the "TC" in TC-104 and the "RUN" in RUN-88 hang off it.
    "key"        varchar(16)  NOT NULL,
    name         varchar(120) NOT NULL,
    description  text,
    engine       varchar(32)  NOT NULL,
    created_at   timestamptz  NOT NULL,
    updated_at   timestamptz  NOT NULL,
    version      bigint       NOT NULL DEFAULT 0,
    CONSTRAINT uq_projects_key UNIQUE (workspace_id, "key"),
    CONSTRAINT ck_projects_engine CHECK (engine IN ('PLAYWRIGHT'))
);

CREATE INDEX idx_projects_workspace ON projects (workspace_id, updated_at DESC);

CREATE TABLE git_repositories (
    id             uuid         PRIMARY KEY,
    workspace_id   uuid         NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    project_id     uuid         NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    provider       varchar(32)  NOT NULL,
    remote_url     varchar(500) NOT NULL,
    default_branch varchar(200) NOT NULL,
    -- Points at the stored credential; the token itself never lands in this table.
    credential_id  varchar(200),
    created_at     timestamptz  NOT NULL,
    updated_at     timestamptz  NOT NULL,
    version        bigint       NOT NULL DEFAULT 0,
    CONSTRAINT uq_git_repositories_project UNIQUE (project_id),
    CONSTRAINT ck_git_repositories_provider CHECK (provider IN ('GITHUB', 'GITLAB', 'BITBUCKET'))
);

CREATE TABLE environments (
    id           uuid         PRIMARY KEY,
    workspace_id uuid         NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    project_id   uuid         NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    name         varchar(64)  NOT NULL,
    base_url     varchar(500) NOT NULL,
    is_default   boolean      NOT NULL DEFAULT false,
    created_at   timestamptz  NOT NULL,
    updated_at   timestamptz  NOT NULL,
    version      bigint       NOT NULL DEFAULT 0,
    CONSTRAINT uq_environments_name UNIQUE (project_id, name)
);

-- is_secret rows hold ciphertext, decrypted only when a job is dispatched to the runner and
-- masked in anything the run captures.
CREATE TABLE environment_vars (
    id             uuid         PRIMARY KEY,
    workspace_id   uuid         NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    environment_id uuid         NOT NULL REFERENCES environments (id) ON DELETE CASCADE,
    "key"          varchar(120) NOT NULL,
    value          text         NOT NULL,
    is_secret      boolean      NOT NULL DEFAULT false,
    created_at     timestamptz  NOT NULL,
    updated_at     timestamptz  NOT NULL,
    version        bigint       NOT NULL DEFAULT 0,
    CONSTRAINT uq_environment_vars_key UNIQUE (environment_id, "key")
);
